mysql:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: omeka
    MYSQL_DATABASE: omeka
    MYSQL_USER: omeka
    MYSQL_PASSWORD: omeka
postfix:
  image: ccnmtl/postfix
omeka:
  image: ccnmtl/omeka
  ports:
    - "8880:80"
  links:
    - mysql
    - postfix
  environment:
    MYSQL_DBNAME: omeka
    MYSQL_USER: omeka
    MYSQL_PASSWORD: omeka
